MvcLotterJacky/Controllers/AwardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLotterModel;
using MvcLotterModel.Page;
using MvcLotterServicesLogic;

namespace MvcLotterJacky.Controllers
{
    public class AwardsController : Controller
    {
        private readonly AwardsListLogic _awardsListLogic=new AwardsListLogic();
        private readonly object _lockobject = new object();
        //
        // GET: /Awards/
        public ActionResult Index(AwardsListEntity objEntity)
        {
            ViewBag.userInfoPar = objEntity;
            var page = _awardsListLogic.GetAwardsListpageList(objEntity);
            var pv = new PageResult<AwardsListEntity>();
            pv.PageIndex = objEntity.PageIndex;
            pv.PageSize = objEntity.PageSize;
            pv.DataList = page ?? new List<AwardsListEntity>();
            pv.Total = page != null && page.Count >= 0 ? Convert.ToInt32(page[0].Total) : 0;
            pv.RequestUrl = objEntity.RequetUrl;
            return View(pv);
        }

        public ActionResult Add()
        {
            return View();
        }


        public object InsertAwards(string Awards, int AwardsNum, string AwardsGoods)
        {
            if (string.IsNullOrEmpty(Awards))
            {
                return Json(new { status = -1, msg = "奖品等级不能为空！" });
            }
            lock (_lockobject)
            {
                var resp = _awardsListLogic.GetAwardsListByAwards(Awards);
                if (resp != null) return Json(new { status = -1, msg = "该奖品等级已经设置过！" });
                var m = new AwardsListEntity()
                {
                    Awards = Awards,
                    AwardsNum = AwardsNum,
                    UsedNum=AwardsNum,
                    AwardsGoods = AwardsGoods
                };
                var data = _awardsListLogic.InsertAwards(m);
                return data > 0 ? Json(new { status = 1, msg = "奖品设置成功" }) : Json(new { status = -1, msg = "奖品设置失败" });
            }
        }

        public object DelAwards(long id)
        {
            var data = _awardsListLogic.DelAwardsList(id);
            return data > 0 ? Json(new { status = 1, msg = "删除成功" }) : Json(new { status = -1, msg = "删除失败" });
        }
	}
}

MvcLotterJacky/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLotterServicesLogic;

namespace MvcLotterJacky.Controllers
{
    public class HomeController : Controller
    {
        private readonly AwardsListLogic _awardsListLogic = new AwardsListLogic();
        private readonly object _lockobject = new object();
        //
        // GET: /抽奖页面
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }
	}
}

MvcLotterJacky/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLotterModel;
using MvcLotterModel.Page;
using MvcLotterModel.ParView;
using MvcLotterServicesLogic;

namespace MvcLotterJacky.Controllers
{
    public class UserController : Controller
    {
        private readonly UserLogic _userLogic = new UserLogic();
        private readonly object _lockobject = new object();
        //
        // GET: /User/
        public ActionResult Index(User objUser)
        { 
            ViewBag.userInfoPar = objUser;
            var page = _userLogic.QueueUserlistpage(objUser);
            var pv = new PageResult<User>();
            pv.PageIndex = objUser.PageIndex;
            pv.PageSize = objUser.PageSize;
            pv.DataList = page ?? new List<User>(); ;
            pv.Total = page != null && page.Count >= 0 ? Convert.ToInt32(page[0].Total) : 0;
            pv.RequestUrl = objUser.RequetUrl;
            return View(pv);
        }

        public ActionResult Add()
        {
            return View();
        }
        //签到
        public object UserSign(long id)
        {
            var data = _userLogic.UpdateUserbyId(id);
            return data > 0 ? Json(new { status = 1, msg = "签到成功" }) : Json(new { status = -1, msg = "签到失败" });
        }
        /// <summary>
        /// 新增员工资料
        /// </summary>
        /// <param name="userNo"></param>
        /// <param name="userName"></param>
        /// <param name="phone"></param>
        /// <param name="department"></param>
        /// <returns></returns>
        public object InsertUser(string userNo, string userName, string phone, string department)
        {
            if (string.IsNullOrEmpty(userNo))
            {
                return Json(new {status = -1, msg = "员工编号不能为空"});
            }
            
            lock (_lockobject)
            {

                var resp = _userLogic.QueueUserlist(userNo);
                if (resp != null) return Json(new { status = -1, msg = "该员工已经存在！" }); 
                var m = new User()
                {
                    UserNo = userNo,
                    UserName = userName,
                    phone = phone,
                    Department = department,
                    Islottery = false,
                    IsSign = false
                };
                var data = _userLogic.Inseruser(m);
                return data > 0 ? Json(new { status = 1, msg = "新增员工成功" }) : Json(new { status = -1, msg = "新增员工失败" });
            }
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public object DelAwards(long id)
        {
            var data = _userLogic.DeleteUserById(id);
            return data > 0 ? Json(new { status = 1, msg = "删除成功" }) : Json(new { status = -1, msg = "删除失败" });
        }
    }
}

MvcLotterJacky/Views/Awards/Index.cshtml
@{
    ViewBag.Title = "奖品设置列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userPar = ViewBag.userInfoPar as MvcLotterModel.AwardsListEntity;
}
<link href="~/Static/searchbar/searchbar.css" rel="stylesheet" />
<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <form id="searchForm" class="form-horizontal " role="form" action="@Url.Action("Index", "Awards")">
                <div class="form-group f-bb">
                    <div class="search-bar clearfix">
                        <div class="row f-fl clearfix f-mr20 f-mb20">
                            <label class="lb f-fl">奖品等级：</label>
                            <select class="form-control" id="Awards" name="Awards" style="width:120px;">
                                <option value="">==请选择==</option>
                                <option value="特等奖">特等奖</option>
                                <option value="一等奖">一等奖</option>
                                <option value="二等奖">二等奖</option>
                                <option value="三等奖">三等奖</option>
                                <option value="四等奖">四等奖</option>
                                <option value="五等奖">五等奖</option>
                                <option value="阳光普照奖">阳光普照奖</option>
                            </select>
                        </div>

                        <div class="row f-fl clearfix f-mr10 f-mb10">
                            &nbsp;
                            <button class="btn btn-sm  btn-primary"><i class="icon-zoom-in bigger-110"></i>查 询 </button>
                            <button class="btn btn-sm reset" type="reset"><i class="icon-undo bigger-110"></i>重置</button>
                        </div>

                    </div>

                </div>

            </form>
            <p>
                <button class="btn btn-sm btn-success" id="btn-add"><i class="icon-inbox bigger-125"></i>设置奖品等级</button>
            </p>
            <div class="table-responsive">
                <div class="dataTables_wrapper" role="grid">
                    <table id="sample-table-1" class="table table-striped  table-bordered table-hover">
                        <thead>
                            <tr role="row">
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">奖品等级</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">奖品数量</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">可使用数量</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">物品</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">创建时间</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">操作</th>
                            </tr>
                        </thead>
                        <tbody role="alert" aria-live="polite" aria-relevant="all" class="table-tr-click">
                            @if (Model.DataList.Count <= 0)
                            {
                                <tr id="odd" class="odd">
                                    <td colspan="15" style="color: red; text-align: center;">暂无奖品信息</td>
                                </tr>
                            }
                            @foreach (MvcLotterModel.AwardsListEntity item in Model.DataList)
                            {
                                <tr>
                                    <td>
                                        @item.Awards
                                    </td>
                                    <td>
                                        @item.AwardsNum
                                    </td>
                                    <td>
                                        @item.UsedNum
                                    </td>
                                    <td>
                                        @item.AwardsGoods
                                    </td>
                                    <td>
                                        @item.CreateTime
                                    </td>
                                    <td>
                                        <button class="btn btn-xs btn-danger open-event redirectionOrder sign" userno="@item.ID" title="删除">
                                            <i class="icon-remove bigger-120"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div>
                @Html.Raw(Model.PagerHtml()) 共 @Model.Total 条
            </div>

            <div class="hr hr-18 dotted hr-double"></div>
        </div>
    </div>

</div>


<script src="~/Static/layer/layer.js"></script>
<script type="text/javascript">

    $(function () {
        //初始化tooltip
        $(".open-event").tooltip({
            show: {
                effect: "slideDown",
                delay: 250
            }
        });

        //保持搜索条件
        $('#Awards').val('@userPar.Awards');

        $("#btn-add").on('click', function () {
            window.location.href = "/Awards/Add";
        });
        //删除
        $(".sign").on("click", function () {
            var id = $(this).attr("userno");
            if (id != undefined) {
                layer.confirm('您确认删除该奖品吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function () {
                    var params = { id: id };
                    $.post("@Url.Action("DelAwards", "Awards")", params, function (data) {
                        if (data.status == 1) {
                            location.reload();
                            layer.msg(data.msg);
                        } else {
                            layer.msg(data.msg);
                        }
                    });
                }, function () {
                    layer.msg('您已经取消了操作');
                });
            } else {
                layer.msg('当前操作无效');
            }

        });

    });
</script>


MvcLotterJacky/Views/Home/Index.cshtml
@{ ViewBag.Title = "管理列表"; Layout = "~/Views/Shared/_Layout.cshtml"; }


<link href="~/Static/searchbar/searchbar.css" rel="stylesheet" />
<style type="text/css">
    .hw-overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0,0,0,0.3);
        z-index: 10;
    }

    .hw-layer-wrap {
        box-sizing: border-box;
        width: 570px;
        position: absolute;
        left: 50%;
        top: 50%;
        margin-left: -285px;
        border-radius: 3px;
        background-color: #fff;
        box-shadow: 1px 2px 4px 0 rgba(0,0,0,0.12);
        padding: 45px 50px;
    }

    .hwLayer-close {
        position: absolute;
        right: 20px;
        top: 20px;
        width: 20px;
        height: 20px;
        cursor: pointer;
        font-size: 20px;
        color: #ccc;
    }

    .hw-layer-wrap .hw-icon {
        color: #b4d8f3;
        font-size: 86px;
        text-align: center;
    }

    .hw-layer-wrap h4 {
        margin: 5px 0 30px;
        font-size: 24px;
        color: #383c3e;
    }

    .hw-layer-wrap p {
        margin: 30px 0;
        line-height: 22px;
        color: #595d60;
        text-align: left;
    }

    .hw-layer-title {
        height: 32px;
        line-height: 32px;
        font-size: 16px;
        position: absolute;
        left: 20px;
        top: 10px;
        font-weight: bold;
    }

    .hw-layer-wrap {
        width: 550px;
        min-height: 250px;
        margin-left: -175px;
        margin-top: -200px;
        padding: 45px 50px;
        text-align: center;
    }

    .hwLayer-cancel {
        margin-left: 20px;
    }
</style>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="hr hr-18 dotted hr-double"></div>
        </div>
    </div>

</div>

MvcLotterJacky/Views/User/Add.cshtml

@{
    ViewBag.Title = "新增员工";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Static/assets/css/font-awesome.min.css" rel="stylesheet" />


    <div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <div class="page-content">
                <div class="page-header">
                    <h1>
                        新增员工资料
                        <small>
                            <i class="icon-double-angle-right"></i>
                            作为抽奖人员的前期资料
                        </small>
                    </h1>
                </div><!-- /.page-header -->
                <form class="form-horizontal" id="userForm" role="form">
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="UserNo">员工编号：</label>
                        <div class="col-sm-9">
                            <input type="text" name="UserNo" id="UserNo" value="" placeholder="员工编号" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="UserName">员工姓名：</label>
                        <div class="col-sm-9">
                            <input type="text" name="UserName" id="UserName" value="" placeholder="员工姓名" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="phone">手机号：</label>
                        <div class="col-sm-9">
                            <input type="text" name="phone" id="phone" value="" placeholder="输入手机号" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="Department">部门：</label>

                        <div class="col-sm-9">
                            <input type="text" name="Department" id="Department" value="" placeholder="输入部门" />
                        </div>
                    </div>
                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9" style="margin:0 auto;text-align: center">
                            <button class="btn btn-info" type="button">
                                <i class="icon-ok bigger-110"></i>
                                提交
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div><!-- /.row -->
</div>

<script src="~/Static/assets/js/typeahead-bs2.min.js"></script>
<script src="~/Static/layer/layer.js"></script>
<script type="text/javascript">
    $(function () {

        //添加标签
        $(".btn-info").on("click", function () {

            var UserNo = $("#UserNo").val();
            var UserName = $("#UserName").val();
            var phone = $("#phone").val();
            var Department = $("#Department").val();
            if (UserNo == "") {
                layer.msg("请输入员工编号！");
                return false;
            }
            if (UserName == "") {
                layer.msg("请输入员工姓名！");
                return false;
            }
            if (phone == "") {
                layer.msg("请输入手机号码");
                return false;
            }
            if (Department == "") {
                layer.msg("请输入部门！");
                return false;
            } else {
                layer.confirm('您确认该次操作吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function () {
                    layer.load(2, { shade: [0.1, '#fff'] });
                    var params = { UserNo: UserNo, UserName: UserName, phone: phone, Department: Department };
                    $.post("@Url.Action("InsertUser", "User")", params, function (data) {
                        if (data.status == 1) {
                            layer.msg(data.msg, {
                                icon: 1,
                                time: 2000
                            }, function () {
                                //parent.layer.close(index);
                                window.location.reload();

                            });
                        } else {
                            layer.msg(data.msg,{icon:2,time:2000},function() {
                                $("#userForm")[0].reset();
                                layer.closeAll();
                            });  
                        }
                    });
                }, function () {
                    layer.msg('您已经取消了操作');
                });

            }

        });
    })
</script>



MvcLotterJacky/Views/User/Index.cshtml
@{
    ViewBag.Title = "用户列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userPar = ViewBag.userInfoPar as MvcLotterModel.User;
}
<link href="~/Static/searchbar/searchbar.css" rel="stylesheet" />
<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <form id="searchForm" class="form-horizontal " role="form" action="@Url.Action("Index", "User")">
                <div class="form-group f-bb">
                    <div class="search-bar clearfix">
                        <div class="row f-fl clearfix f-mr20 f-mr20">
                            <label class="lb f-fl">员工工号：</label>
                            <input type="text" id="UserNo" name="UserNo" placeholder="工号" class="f-fl ipt" />
                        </div>
                        <div class="row f-fl clearfix f-mr20 f-mr20">
                            <label class="lb f-fl">员工手机号：</label>
                            <input type="text" id="Phone" name="Phone" placeholder="手机号" class="f-fl ipt" />
                        </div>
                        <div class="row f-fl clearfix f-mr20 f-mb20">
                            <label class="lb f-fl">员工姓名：</label>
                            <input type="text" id="UserName" name="UserName" placeholder="姓名" class="f-fl ipt" />
                        </div>
                        <div class="row f-fl clearfix f-mr20 f-mb20">
                            <label class="lb f-fl">是否签到：</label>
                            <select class="form-control" id="IsSign" name="IsSign" style="width:120px;">
                                <option value="">==请选择==</option>
                                <option value="false">未签到</option>
                                <option value="true">已签到</option>
                            </select>
                        </div>

                        <div class="row f-fl clearfix f-mr10 f-mb10">
                            &nbsp;
                            <button class="btn btn-sm  btn-primary"><i class="icon-zoom-in bigger-110"></i>查 询 </button>
                            <button class="btn btn-sm reset" type="reset"><i class="icon-undo bigger-110"></i>重置</button>
                        </div>

                    </div>

                </div>

            </form>
            <p>
                <button class="btn btn-sm btn-success" id="btn-add"><i class="icon-inbox bigger-125"></i>新增员工</button>
            </p>
            <div class="table-responsive">
                <div class="dataTables_wrapper" role="grid">
                    <table id="sample-table-1" class="table table-striped  table-bordered table-hover">
                        <thead>
                            <tr role="row">
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">员工编号</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">员工姓名</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">员工手机号</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">所属部门</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">签到状态</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">创建时间</th>
                                <th role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1">操作</th>
                            </tr>
                        </thead>
                        <tbody role="alert" aria-live="polite" aria-relevant="all" class="table-tr-click">
                            @if (Model.DataList.Count <= 0)
                            {
                                <tr id="odd" class="odd">
                                    <td colspan="15" style="color: red; text-align: center;">暂无人员信息</td>
                                </tr>
                            }
                            @foreach (MvcLotterModel.User item in Model.DataList)
                            {
                                <tr>
                                    <td>
                                        @item.UserNo
                                    </td>
                                    <td>
                                        @item.UserName
                                    </td>
                                    <td>
                                        @item.phone
                                    </td>
                                    <td>
                                        @item.Department
                                    </td>
                                    <td>
                                        @Html.Raw(item.IsSignStr)
                                    </td>
                                    <td>
                                        @item.CreateTime
                                    </td>
                                    <td>
                                        <button class="btn btn-xs btn-danger open-event redirectionOrder del" userno="@item.ID" title="删除">
                                            <i class="icon-remove bigger-120"></i>
                                        </button>
                                        @if (item.IsSign == false)
                                        {

                                            <button class="btn btn-xs btn-pink open-event redirectionOrder sign" userno="@item.ID" title="签到">
                                                <i class="icon-exchange bigger-120"></i>
                                            </button>

                                        }
                                       
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div>
                @Html.Raw(Model.PagerHtml()) 共 @Model.Total 条
            </div>

            <div class="hr hr-18 dotted hr-double"></div>
        </div>
    </div>

</div>


<script src="~/Static/layer/layer.js"></script>
<script type="text/javascript">

    $(function () {
        //初始化tooltip
        $(".open-event").tooltip({
            show: {
                effect: "slideDown",
                delay: 250
            }
        });

        //保持搜索条件
        $('#UserNo').val('@userPar.UserNo');
        $('#Phone').val('@userPar.phone');
        $('#IsSign').val('@userPar.IsSignState');
        $('#UserName').val('@userPar.UserName');

        $("#btn-add").on('click', function () {
            window.location.href = "/User/Add";
        });
        //确认
        $(".sign").on("click", function () {
            var id = $(this).attr("userno");
            if (id != undefined) {

                layer.confirm('您确认该用户已经入场了吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function () {
                    var params = { id: id };
                    $.post("@Url.Action("UserSign", "User")", params, function (data) {
                        if (data.status == 1) {
                            location.reload();
                            layer.msg(data.msg);
                        } else {
                            layer.msg(data.msg);
                        }
                    });
                }, function () {
                    layer.msg('您已经取消了操作');
                });
            } else {
                layer.msg('当前操作无效');
            }

        });
        //删除
        $(".del").on("click", function () {
            var id = $(this).attr("userno");
            if (id != undefined) {

                layer.confirm('您确认删除该用户吗？', {
                    btn: ['确认', '取消'] //按钮
                }, function () {
                    var params = { id: id };
                    $.post("@Url.Action("DelAwards", "User")", params, function (data) {
                        if (data.status == 1) {
                            layer.msg(data.msg, {
                                icon: 5,
                                time: 2000
                            }, function () {
                                //parent.layer.close(index);
                                window.location.reload();

                            });
                        } else {
                            layer.msg(data.msg);
                        }
                    });
                }, function () {
                    layer.msg('您已经取消了操作');
                });
            } else {
                layer.msg('当前操作无效');
            }

        });

    });
</script>
